M48
; DRILL file {KiCad (7.0.0-0)} date Wednesday, March 08, 2023 at 11:01:28 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-08T23:01:28-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0906
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1654
%
G90
G05
T1
X-0.3937Y-0.7874
X0.3937Y-0.7874
T2
X-1.063Y0.5512
X0.0Y-1.1417
X1.063Y0.5512
T0
M30
