M48
; DRILL file {KiCad (7.0.0-0)} date Sunday, April 09, 2023 at 10:27:31 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-09T22:27:31-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1102
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1496
%
G90
G05
T1
X0.0Y-0.8268
T2
X-0.9646Y0.5315
X0.0Y-0.5315
X0.9646Y0.5315
T3
X-0.4724Y-0.748
X0.4724Y-0.748
T0
M30
