M48
; DRILL file {KiCad (7.0.0-0)} date Tuesday, March 14, 2023 at 10:07:24 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-14T22:07:24-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1693
%
G90
G05
T1
X-0.9677Y0.0
X-0.5677Y0.0
X-0.2Y0.0
X0.2Y0.0
X0.5677Y0.0
X0.9677Y0.0
T2
X-1.063Y0.5512
X0.0Y-1.1417
X1.063Y0.5512
T3
X-0.4331Y-0.5512
X0.4331Y-0.5512
T0
M30
