M48
; DRILL file {KiCad (7.0.0-0)} date Monday, March 27, 2023 at 01:09:40 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-27T01:09:40-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1102
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1496
%
G90
G05
T1
X0.0Y-0.9055
T2
X-0.9646Y0.5315
X0.0Y-0.5118
X0.9646Y0.5315
T3
X-0.4724Y-0.7874
X0.4724Y-0.7874
T0
M30
