M48
; DRILL file {KiCad 7.0.5} date Fri Mar 22 09:53:21 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-22T09:53:21-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1693
%
G90
G05
T1
X-0.95Y0.0
X-0.55Y0.0
X-0.2Y0.0
X0.2Y0.0
X0.55Y0.0
X0.95Y0.0
T2
X-0.9055Y0.4724
X-0.5118Y-0.4724
X-0.375Y0.0
X0.375Y0.0
X0.5118Y-0.4724
X0.9055Y0.4724
T3
X0.0Y-0.9843
T0
M30
