M48
; DRILL file {KiCad 7.0.5} date Fri Jul 14 01:07:39 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-14T01:07:39-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1693
%
G90
G05
T1
X-0.95Y0.0
X-0.55Y0.0
X-0.2Y0.0
X0.2Y0.0
X0.55Y0.0
X0.95Y0.0
T2
X-0.374Y-0.5315
X0.374Y-0.5315
T3
X0.0Y-0.9843
T0
M30
