M48
; DRILL file {KiCad 7.0.5} date Sun Mar 24 10:35:58 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-24T10:35:58-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1772
%
G90
G05
T1
X-1.187Y0.0
X1.187Y0.0
T2
X-0.5512Y-0.748
X0.0Y-0.748
X0.5512Y-0.748
T0
M30
