M48
; DRILL file {KiCad (7.0.0-0)} date Sunday, April 23, 2023 at 03:59:43 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-23T03:59:43-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1693
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.2520
%
G90
G05
T1
X-0.95Y0.0
X-0.55Y0.0
X-0.2Y0.0
X0.2Y0.0
X0.55Y0.0
X0.95Y0.0
T2
X0.0Y-0.9843
T3
X-0.9252Y0.4724
X0.9252Y0.4724
T0
M30
